server:
  http:
    port: 8082
    mode: production

database:
  type: postgresql
  host: localhost
  port: 5432
  username: cbE8Eg2ukBD7u6yxuhXkqZb8vCS3bhCN
  password: 29q4wSumbF3QG2wEaAtynKNtvcEf4nfc
  name: CoreService

registry:
  host: localhost
  port: 5001
  username: HerMBujLXjt7PhUcENjmyGT8PJmdCYcY
  password: K6WSUNxFELBM2WZRF86Lx72g5FREUrym

sentry:
  dsn: ""