version: '3.9'

services: 
  registry:
    restart: unless-stopped
    image: registry:2
    container_name: registry
    ports:
      - "5001:5001"
    volumes:
      - ./certs:/certs
      - ./auth:/auth
    environment:
      REGISTRY_HTTP_ADDR: ":5001"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_SECRET: hRLexzzZe2qJbkuMKhUet9DjvpNUYTq7
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: zULeNdGAmeCAHmQjJfVgBZ7AZTSy8BLP
      REGISTRY_STORAGE_S3_SECRETKEY: wGwt4Pr2Y9sCQUFCEYS7Ccn4FZT2kEn7
      REGISTRY_STORAGE_S3_REGIONENDPOINT: minio:9000
      REGISTRY_STORAGE_S3_BUCKET: registry
      REGISTRY_STORAGE_S3_REGION: local
      REGISTRY_STORAGE_S3_SECURE: "false"
      REGISTRY_STORAGE_REDIRECT_DISABLE: "true"
      REGISTRY_REDIS_ADDR: redis:6379
      REGISTRY_REDIS_PASSWORD: ScjUY35BRvmpY5wvu6T6ryWtx9kuZLRP
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      REGISTRY_LOG_LEVEL: info
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    depends_on:
      - minio
      - redis

  minio:
    restart: unless-stopped
    image: minio/minio
    container_name: minio
    volumes:
      - s3_data:/data
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: zULeNdGAmeCAHmQjJfVgBZ7AZTSy8BLP
      MINIO_SECRET_KEY: wGwt4Pr2Y9sCQUFCEYS7Ccn4FZT2kEn7
      MINIO_REGION_NAME: local
    entrypoint: /bin/sh
    command: -c 'mkdir -p /data/registry && /usr/bin/minio server /data'

  redis:
    restart: unless-stopped
    image: redis:6.0-alpine
    container_name: redis
    expose:
      - 6379
    command: redis-server --requirepass ScjUY35BRvmpY5wvu6T6ryWtx9kuZLRP

  postgres:
    restart: unless-stopped
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: cbE8Eg2ukBD7u6yxuhXkqZb8vCS3bhCN
      POSTGRES_PASSWORD: 29q4wSumbF3QG2wEaAtynKNtvcEf4nfc
      POSTGRES_DB: CoreService
    expose:
      - 5432
    ports:
      - "5432:5432"

  mariadb:
    restart: unless-stopped
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: CoreService
      MYSQL_USER: Q2TXf8UyR36Jy4CmRK4c6sGx9rKnEkuj
      MYSQL_PASSWORD: wd8HSPCX7j9LXFdzUvYZL8zqg3xgV2ET
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    expose:
      - 3306
    ports:
      - "3306:3306"

  adminer:
    restart: unless-stopped
    image: adminer:4.7
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: price
    ports:
      - 8080:8080

volumes:
  s3_data:
  postgres_data:
  mariadb_data:
