name: Go develop

on:
  push:
    branches:
      - feature/*
      - develop

jobs:
#  sonar:
#    name: SonarQube
#    runs-on: ubuntu-18.04
#    steps:
#      - name: Git checkout
#        uses: actions/checkout@v2
#
#      - name: SonarCloud scan
#        uses:  kitabisa/sonarqube-action@master
#        with:
#          projectBaseDir: .
#          host: ${{ secrets.SONARQUBE_HOST }}
#          login: ${{ secrets.SONARQUBE_TOKEN }}

#  build:
#    name: Build
#    runs-on: ubuntu-18.04
#    env:
#      CGO_ENABLED: 0
#      GOOS: linux
#      GOARCH: amd64
#    steps:
#      - name: Git checkout
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.15.6'
#
#      - name: Get dependencies
#        run: |
#          go get -v -t -d ./...
#          go build ./internal/imports
#
#      - name: Build
#        run: go build -v -a -installsuffix cgo
#
#      - name: Test
#        run: go test -v

  deliver:
    name: Deliver
#    needs: [build, sonar]
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: harbor.cloud.feddema.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1