name: Go feature

on:
  push:
    branches:
      - feature/*

jobs:
  sonar:
    name: SonarQube
    runs-on: ubuntu-18.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: SonarCloud scan
        uses:  kitabisa/sonarqube-action@master
        with:
          projectBaseDir: .
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
                 curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                 dep ensure
          fi

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v